package com.ldq.connect.Tools;

import com.ldq.Utils.DataUtils;

import java.util.HashMap;

public class Pinyin {
    static HashMap<String,String> map = new HashMap();
    static String PingyinList = "a\n" +
            "ai\n" +
            "an\n" +
            "ang\n" +
            "ao\n" +
            "ba\n" +
            "bai\n" +
            "ban\n" +
            "bang\n" +
            "bao\n" +
            "bei\n" +
            "ben\n" +
            "beng\n" +
            "bi\n" +
            "bian\n" +
            "biao\n" +
            "bie\n" +
            "bin\n" +
            "bing\n" +
            "bo\n" +
            "bu\n" +
            "ca\n" +
            "cai\n" +
            "can\n" +
            "cang\n" +
            "cao\n" +
            "ce\n" +
            "cen\n" +
            "ceng\n" +
            "cha\n" +
            "chai\n" +
            "chan\n" +
            "chang\n" +
            "chao\n" +
            "che\n" +
            "chen\n" +
            "cheng\n" +
            "chi\n" +
            "chong\n" +
            "chou\n" +
            "chu\n" +
            "chua\n" +
            "chuai\n" +
            "chuan\n" +
            "chuang\n" +
            "chui\n" +
            "chun\n" +
            "chuo\n" +
            "ci\n" +
            "cong\n" +
            "cou\n" +
            "cu\n" +
            "cuan\n" +
            "cui\n" +
            "cun\n" +
            "cuo\n" +
            "da\n" +
            "dai\n" +
            "dan\n" +
            "dang\n" +
            "dao\n" +
            "de\n" +
            "dei\n" +
            "den\n" +
            "deng\n" +
            "di\n" +
            "dia\n" +
            "dian\n" +
            "diao\n" +
            "die\n" +
            "ding\n" +
            "diu\n" +
            "dong\n" +
            "dou\n" +
            "du\n" +
            "duan\n" +
            "dui\n" +
            "dun\n" +
            "duo\n" +
            "e\n" +
            "ei\n" +
            "en\n" +
            "eng\n" +
            "er\n" +
            "fa\n" +
            "fan\n" +
            "fang\n" +
            "fei\n" +
            "fen\n" +
            "feng\n" +
            "fo\n" +
            "fou\n" +
            "fu\n" +
            "ga\n" +
            "gai\n" +
            "gan\n" +
            "gang\n" +
            "gao\n" +
            "ge\n" +
            "gei\n" +
            "gen\n" +
            "geng\n" +
            "gong\n" +
            "gou\n" +
            "gu\n" +
            "gua\n" +
            "guai\n" +
            "guan\n" +
            "guang\n" +
            "gui\n" +
            "gun\n" +
            "guo\n" +
            "ha\n" +
            "hai\n" +
            "han\n" +
            "hang\n" +
            "hao\n" +
            "he\n" +
            "hei\n" +
            "hen\n" +
            "heng\n" +
            "hong\n" +
            "hou\n" +
            "hu\n" +
            "hua\n" +
            "huai\n" +
            "huan\n" +
            "huang\n" +
            "hui\n" +
            "hun\n" +
            "huo\n" +
            "ji\n" +
            "jia\n" +
            "jian\n" +
            "jiang\n" +
            "jiao\n" +
            "jie\n" +
            "jin\n" +
            "jing\n" +
            "jiong\n" +
            "jiu\n" +
            "ju\n" +
            "juan\n" +
            "jue\n" +
            "jun\n" +
            "ka\n" +
            "kai\n" +
            "kan\n" +
            "kang\n" +
            "kao\n" +
            "ke\n" +
            "ken\n" +
            "keng\n" +
            "kong\n" +
            "kou\n" +
            "ku\n" +
            "kua\n" +
            "kuai\n" +
            "kuan\n" +
            "kuang\n" +
            "kui\n" +
            "kun\n" +
            "kuo\n" +
            "la\n" +
            "lai\n" +
            "lan\n" +
            "lang\n" +
            "lao\n" +
            "le\n" +
            "lei\n" +
            "leng\n" +
            "li\n" +
            "lia\n" +
            "lian\n" +
            "liang\n" +
            "liao\n" +
            "lie\n" +
            "lin\n" +
            "ling\n" +
            "liu\n" +
            "long\n" +
            "lou\n" +
            "lu\n" +
            "luan\n" +
            "lue\n" +
            "lun\n" +
            "luo\n" +
            "lv\n" +
            "lue\n" +
            "m\n" +
            "ma\n" +
            "mai\n" +
            "man\n" +
            "mang\n" +
            "mao\n" +
            "me\n" +
            "mei\n" +
            "men\n" +
            "meng\n" +
            "mi\n" +
            "mian\n" +
            "miao\n" +
            "mie\n" +
            "min\n" +
            "ming\n" +
            "miu\n" +
            "mo\n" +
            "mou\n" +
            "mu\n" +
            "na\n" +
            "nai\n" +
            "nan\n" +
            "nang\n" +
            "nao\n" +
            "ne\n" +
            "nei\n" +
            "nen\n" +
            "neng\n" +
            "ng\n" +
            "ni\n" +
            "nian\n" +
            "niang\n" +
            "niao\n" +
            "nie\n" +
            "nin\n" +
            "ning\n" +
            "niu\n" +
            "nong\n" +
            "nou\n" +
            "nu\n" +
            "nuan\n" +
            "nun\n" +
            "nuo\n" +
            "nv\n" +
            "nue\n" +
            "o\n" +
            "ou\n" +
            "pa\n" +
            "pai\n" +
            "pan\n" +
            "pang\n" +
            "pao\n" +
            "pei\n" +
            "pen\n" +
            "peng\n" +
            "pi\n" +
            "pian\n" +
            "piao\n" +
            "pie\n" +
            "pin\n" +
            "ping\n" +
            "po\n" +
            "pou\n" +
            "pu\n" +
            "qi\n" +
            "qia\n" +
            "qian\n" +
            "qiang\n" +
            "qiao\n" +
            "qie\n" +
            "qin\n" +
            "qing\n" +
            "qiong\n" +
            "qiu\n" +
            "qu\n" +
            "quan\n" +
            "que\n" +
            "qun\n" +
            "ran\n" +
            "rang\n" +
            "rao\n" +
            "re\n" +
            "ren\n" +
            "reng\n" +
            "ri\n" +
            "rong\n" +
            "rou\n" +
            "ru\n" +
            "ruan\n" +
            "rui\n" +
            "run\n" +
            "ruo\n" +
            "sa\n" +
            "sai\n" +
            "san\n" +
            "sang\n" +
            "sao\n" +
            "se\n" +
            "sen\n" +
            "seng\n" +
            "sha\n" +
            "shai\n" +
            "shan\n" +
            "shang\n" +
            "shao\n" +
            "she\n" +
            "shei\n" +
            "shen\n" +
            "sheng\n" +
            "shi\n" +
            "shou\n" +
            "shu\n" +
            "shua\n" +
            "shuai\n" +
            "shuan\n" +
            "shuang\n" +
            "shui\n" +
            "shun\n" +
            "shuo\n" +
            "si\n" +
            "song\n" +
            "sou\n" +
            "su\n" +
            "suan\n" +
            "sui\n" +
            "sun\n" +
            "suo\n" +
            "ta\n" +
            "tai\n" +
            "tan\n" +
            "tang\n" +
            "tao\n" +
            "te\n" +
            "teng\n" +
            "ti\n" +
            "tian\n" +
            "tiao\n" +
            "tie\n" +
            "ting\n" +
            "tong\n" +
            "tou\n" +
            "tu\n" +
            "tuan\n" +
            "tui\n" +
            "tun\n" +
            "tuo\n" +
            "wa\n" +
            "wai\n" +
            "wan\n" +
            "wang\n" +
            "wei\n" +
            "wen\n" +
            "weng\n" +
            "wo\n" +
            "wu\n" +
            "xi\n" +
            "xia\n" +
            "xian\n" +
            "xiang\n" +
            "xiao\n" +
            "xie\n" +
            "xin\n" +
            "xing\n" +
            "xiong\n" +
            "xiu\n" +
            "xu\n" +
            "xuan\n" +
            "xue\n" +
            "xun\n" +
            "ya\n" +
            "yan\n" +
            "yang\n" +
            "yao\n" +
            "ye\n" +
            "yi\n" +
            "yin\n" +
            "ying\n" +
            "yo\n" +
            "yong\n" +
            "you\n" +
            "yu\n" +
            "yuan\n" +
            "yue\n" +
            "yun\n" +
            "za\n" +
            "zai\n" +
            "zan\n" +
            "zang\n" +
            "zao\n" +
            "ze\n" +
            "zei\n" +
            "zen\n" +
            "zeng\n" +
            "zha\n" +
            "zhai\n" +
            "zhan\n" +
            "zhang\n" +
            "zhao\n" +
            "zhe\n" +
            "zhei\n" +
            "zhen\n" +
            "zheng\n" +
            "zhi\n" +
            "zhong\n" +
            "zhou\n" +
            "zhu\n" +
            "zhua\n" +
            "zhuai\n" +
            "zhuan\n" +
            "zhuang\n" +
            "zhui\n" +
            "zhun\n" +
            "zhuo\n" +
            "zi\n" +
            "zong\n" +
            "zou\n" +
            "zu\n" +
            "zuan\n" +
            "zui\n" +
            "zun\n" +
            "zuo";
    static {
        String[] Cuts = PingyinList.split("\n");
        for(String a : Cuts)
        {
            String MD5 = DataUtils.getDataMD5((a.toUpperCase()+"&rareword").getBytes()).substring(0,8);
            map.put(MD5,a);
        }
    }
    public static String GetMD5Pinyin(String md5)
    {

        String up = md5.toUpperCase();
        if(map.containsKey(up))return map.get(up);
        return "";
    }
}
